// GENERATED by scripts/generate-types.mjs — do not edit.
// Source: docs/pb_schema.json
//
// Every file field on the deployed schema, with the limits PocketBase will
// enforce. The upload path checks against these first so a rejection is a
// clear message rather than a 400 from PocketBase after the bytes are sent.
//
// `mimeTypes: []` means the schema places no type restriction on that field.

export interface FileFieldSpec {
  /** 1 means a single file; more means a list. */
  maxSelect: number;
  /** Bytes. 0 means PocketBase's own default applies. */
  maxSize: number;
  /** Empty means any type is accepted. */
  mimeTypes: string[];
  required: boolean;
}

export const FILE_FIELDS = {
  "aia_notices": {
    "attachments": {
      maxSelect: 5,
      maxSize: 52428800,
      mimeTypes: [],
      required: false,
    },
  },
  "change_orders": {
    "attachments": {
      maxSelect: 5,
      maxSize: 52428800,
      mimeTypes: [],
      required: false,
    },
  },
  "daily_logs": {
    "attachments": {
      maxSelect: 10,
      maxSize: 10485760,
      mimeTypes: [],
      required: false,
    },
  },
  "deficiencies": {
    "photos": {
      maxSelect: 5,
      maxSize: 10485760,
      mimeTypes: [],
      required: false,
    },
  },
  "document_revisions": {
    "file": {
      maxSelect: 1,
      maxSize: 104857600,
      mimeTypes: [],
      required: false,
    },
  },
  "drawings": {
    "file": {
      maxSelect: 1,
      maxSize: 104857600,
      mimeTypes: [],
      required: false,
    },
  },
  "project_documents": {
    "file": {
      maxSelect: 1,
      maxSize: 104857600,
      mimeTypes: [],
      required: false,
    },
  },
  "punch_list": {
    "photos": {
      maxSelect: 5,
      maxSize: 10485760,
      mimeTypes: [],
      required: false,
    },
  },
  "rfis": {
    "attachments": {
      maxSelect: 5,
      maxSize: 52428800,
      mimeTypes: [],
      required: false,
    },
  },
  "safety_observations": {
    "photos": {
      maxSelect: 5,
      maxSize: 10485760,
      mimeTypes: [],
      required: false,
    },
  },
  "subcontractors": {
    "documents": {
      maxSelect: 10,
      maxSize: 52428800,
      mimeTypes: [],
      required: false,
    },
  },
  "submittals": {
    "attachments": {
      maxSelect: 10,
      maxSize: 52428800,
      mimeTypes: [],
      required: false,
    },
  },
  "users": {
    "avatar": {
      maxSelect: 1,
      maxSize: 5242880,
      mimeTypes: ["image/jpeg","image/png","image/svg+xml","image/gif","image/webp"],
      required: false,
    },
  },
  "workflow_actions": {
    "attachments": {
      maxSelect: 5,
      maxSize: 52428800,
      mimeTypes: [],
      required: false,
    },
  },
} as const satisfies Record<string, Record<string, FileFieldSpec>>;

/** Collections that have at least one file field. */
export type FileCollection = keyof typeof FILE_FIELDS;

export function fileFieldsFor(collection: string): Record<string, FileFieldSpec> {
  return (FILE_FIELDS as Record<string, Record<string, FileFieldSpec>>)[collection] ?? {};
}
